// <auto-generated />
using AstrolojiApp.Data.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstrolojiApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoroscopeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutText = "Burç yorumları, astrolojik analizler ve kişisel harita rehberliğiyle hayatınızı daha iyi anlayın. Günlük, haftalık ve aylık burç yorumlarınızı hemen öğrenin. Astrolojiye dair her şey burada! Günlük burç yorumları, gezegen konumları, yükselen burçlar ve kişisel astroloji analiziyle hayatınızı yönlendirin. Burçlarınızı ve gezegen hareketlerini keşfedin. Günlük yorumlarla hayatınızda ne gibi değişiklikler olabileceğini öğrenin ve astrolojik rehberlikle geleceğinizi şekillendirin.",
                            BrandName = "Bir Başka Yol",
                            Email = "gokyuzunebakiyoruz@org.com",
                            HoroscopeName = "Koç, Boğa, İkizler, Yengeç, Aslan, Başak, Terazi, Akrep, Yay, Oğlak, Kova, Balık",
                            ImageUrl = "/Ui/assets/img/photoast.jpg",
                            PhoneNumber = "0212 000 0000",
                            Title = "Yıldızlarınız Söylesin, Hayatınızı Keşfedin!",
                            WorkingHours = "Çalışma Saatleri: Salı - Ctesi: 10.00 - 19.00 | Pazar - Ptesi: Tatil"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.AstrologComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AstrologComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/Ui/assets/img/aylin.jpg",
                            Name = "Aylin Yıldız",
                            Text = "2024 yılı, gökyüzünde birçok önemli gezegen hareketi ve tutulmalar ile dikkat çekiyor. Özellikle Yengeç ve Koç burçları için önemli bir yıl olacak. Yengeçler, ailevi ilişkilerde önemli dönüşümler yaşayacak, Koçlar ise iş ve kariyer alanında büyük atılımlar yapabilirler. Venüs’ün Balık burcundaki hareketi, romantik ilişkilerde duygusal derinliği artırırken, Uranüs’ün Boğa burcunda ilerlemesi finansal anlamda yenilikçi yaklaşımlara açık bir yılı işaret ediyor. Bu yıl, kendinize güvenin ve karşınıza çıkan fırsatları değerlendirmekten çekinmeyin."
                        },
                        new
                        {
                            Id = 2,
                            Image = "/Ui/assets/img/burak.jpg",
                            Name = "Burak Demir",
                            Text = "2024 yılı, değişim ve yenilik yılı olacak. Özellikle burçlar arasında Boğa, Akrep ve Kova burçları, Uranüsün etkisiyle kendilerini yeniden şekillendirecekler. Boğalar, mali anlamda radikal kararlar alabilirken, Akrepler ise psikolojik ve duygusal yenilenmeye adım atacaklar. Kova burçları için ise toplumsal bağlamda önemli değişiklikler ve sosyal projeler devreye girebilir. Bu yıl, eski kalıpları kırmak ve kendi yolunuzu çizmek için harika bir fırsat sunuyor. Hayatınızda yeni başlangıçlar yapma zamanı geldi."
                        },
                        new
                        {
                            Id = 3,
                            Image = "/Ui/assets/img/cetin.jpg",
                            Name = "Çetin Aydın",
                            Text = "2024 yılı, iş ve kariyer anlamında önemli adımlar atmak için çok uygun bir zaman dilimi. Özellikle Aslan, Oğlak ve Terazi burçları için bu yıl, profesyonel hayatlarında hızlı yükselme ve önemli fırsatlar barındırıyor. Aslanlar liderlik yeteneklerini daha da pekiştirirken, Oğlaklar uzun vadeli planlarını hayata geçirebilir. Teraziler ise işbirlikleri ve ortaklıklar konusunda dikkatli olmalılar, çünkü bu yıl doğru partnerlerle güçlü bağlantılar kurmak, başarılı olmanızda anahtar rol oynayacak. Finansal anlamda ise dikkatli yatırım yapmanın tam zamanı."
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kadıköy",
                            Icon = "bi bi-geo-alt-fill",
                            Map = "",
                            PhoneNumber = "02120003131"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.DailyNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DailyNews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Geçmiş deneyimlerden ders çıkarma  ve iletişimle ilgili önemli bir dönemdeyiz. Bu dönemde geleceğe yönelik planlar yapmak ve projeler geliştirmek için uygun bir zaman olabilir. Kararlarınızı, fikirlerinizi değiştirecek insanlar, kitaplar, eğitimlerle karşılaşabilir, sohbetler edebilirsiniz. Yeni fikirler, düşünceler ve bilgilerle karşılaşabiliriz ki bu da bizi hayat amaçlarımza uyumlu bir yola yönlendirebilir. Daha önce göz ardı ettiğimiz veya farkında olmadığımız konulara ilgi duymaya başlayabiliriz.",
                            Title = "Merkür ile Kuzey Ay Düğümü arasında kavuşum açısı olacak. Etki süresi 2 gün!!"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.Horoscope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Horoscopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRange = "21 Mart - 20 Nisan",
                            Image = "/Ui/assets/img//Koc.jpg",
                            Name = "Koç"
                        },
                        new
                        {
                            Id = 2,
                            DateRange = "21 Nisan - 20 Mayıs",
                            Image = "/Ui/assets/img//Boga.jpg",
                            Name = "Boğa"
                        },
                        new
                        {
                            Id = 3,
                            DateRange = "21 Mayıs - 21 Haziran",
                            Image = "/Ui/assets/img/ikizler.jpg",
                            Name = "İkizler"
                        },
                        new
                        {
                            Id = 4,
                            DateRange = "22 Haziran - 22 Temmuz",
                            Image = "/Ui/assets/img/Yengec.jpg",
                            Name = "Yengeç"
                        },
                        new
                        {
                            Id = 5,
                            DateRange = "23 Temmuz - 22 Ağustos",
                            Image = "/Ui/assets/img/Aslan.jpg",
                            Name = "Aslan"
                        },
                        new
                        {
                            Id = 6,
                            DateRange = "23 Ağustos - 22 Eylül",
                            Image = "/Ui/assets/img/Basak.jpg",
                            Name = "Başak"
                        },
                        new
                        {
                            Id = 7,
                            DateRange = "23 Eylül - 22 Ekim",
                            Image = "/Ui/assets/img/Terazi.jpg",
                            Name = "Terazi"
                        },
                        new
                        {
                            Id = 8,
                            DateRange = "23 Ekim - 21 Kasım",
                            Image = "/Ui/assets/img/Akrep.jpg",
                            Name = "Akrep"
                        },
                        new
                        {
                            Id = 9,
                            DateRange = "22 Kasım - 21 Aralık",
                            Image = "/Ui/assets/img/Yay.jpg",
                            Name = "Yay"
                        },
                        new
                        {
                            Id = 10,
                            DateRange = "22 Aralık - 19 Ocak",
                            Image = "/Ui/assets/img/Oglak.jpg",
                            Name = "Oğlak"
                        },
                        new
                        {
                            Id = 11,
                            DateRange = "20 Ocak - 18 Şubat",
                            Image = "/Ui/assets/img/Kova.jpg",
                            Name = "Kova"
                        },
                        new
                        {
                            Id = 12,
                            DateRange = "19 Şubat - 20 Mart",
                            Image = "/Ui/assets/img/balik.jpg",
                            Name = "Balık"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.HoroscopeComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Annual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoroscopeId")
                        .HasColumnType("int");

                    b.Property<string>("Monthly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoroscopeId");

                    b.ToTable("HoroscopeComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Annual = "2024 yılı sizin için yeni başlangıçların yılı olacak. Mars'ın etkisiyle hedeflerinize ulaşmak için güçlü bir motivasyona sahip olacaksınız.",
                            Daily = "Bugün enerjiniz yüksek olacak. İş hayatınızda yeni fırsatlar karşınıza çıkabilir. Spor yapmak için uygun bir gün.",
                            HoroscopeId = 1,
                            Monthly = "Bu ay kariyer hayatınızda önemli gelişmeler yaşanabilir. Finansal konularda temkinli olun.",
                            Name = "Koç Burcu"
                        },
                        new
                        {
                            Id = 2,
                            Annual = "2024, özellikle kariyer ve eğitim alanlarında başarılı olacağınız bir yıl. Venüs desteğiyle aşk hayatınız canlanacak.",
                            Daily = "Maddi konularda şanslı bir gündesiniz. Venüs'ün etkisiyle aşk hayatınızda güzel gelişmeler olabilir.",
                            HoroscopeId = 2,
                            Monthly = "Mayıs ayı boyunca finansal konularda şanslı olacaksınız. Yeni yatırım fırsatları değerlendirebilirsiniz.",
                            Name = "Boğa Burcu"
                        },
                        new
                        {
                            Id = 3,
                            Annual = "2024'te eğitim ve seyahat konularında şanslı olacaksınız. İkili ilişkilerinizde önemli kararlar alabilirsiniz.",
                            Daily = "İletişim yetenekleriniz üst düzeyde. Sosyal ilişkilerinizde başarılı olacaksınız.",
                            HoroscopeId = 3,
                            Monthly = "Merkür'ün etkisiyle iletişim alanında başarılı olacağınız bir ay. Yeni projeler başlatabilirsiniz.",
                            Name = "İkizler Burcu"
                        },
                        new
                        {
                            Id = 4,
                            Annual = "2024 yılı, özellikle aile ve ev yaşamınızda önemli değişimlerin yaşanacağı bir dönem olacak.",
                            Daily = "Duygusal konularda hassas bir gün. Ailenizle ilgili güzel gelişmeler yaşayabilirsiniz.",
                            HoroscopeId = 4,
                            Monthly = "Ay'ın etkisiyle duygusal konularda derin düşüneceğiniz bir ay. Ev ve aile konularında önemli kararlar alabilirsiniz.",
                            Name = "Yengeç Burcu"
                        },
                        new
                        {
                            Id = 5,
                            Annual = "2024'te kariyerinizde yükseliş var. Güneş'in desteğiyle başarıdan başarıya koşacaksınız.",
                            Daily = "Güneş'in etkisiyle kariyerinizde parlayacağınız bir gün. Liderlik özellikleriniz ön planda.",
                            HoroscopeId = 5,
                            Monthly = "Temmuz ayı sizin için oldukça verimli geçecek. Yaratıcı projeleriniz için destek bulabilirsiniz.",
                            Name = "Aslan Burcu"
                        },
                        new
                        {
                            Id = 6,
                            Annual = "2024, sağlık ve iş hayatınızda olumlu gelişmelerin yaşanacağı bir yıl olacak.",
                            Daily = "Detaylara olan hakimiyetiniz işinizde başarı getirecek. Sağlık konularına dikkat.",
                            HoroscopeId = 6,
                            Monthly = "Merkür retrosu sizi olumlu etkileyecek. İş hayatınızda yeni düzenlemeler yapabilirsiniz.",
                            Name = "Başak Burcu"
                        },
                        new
                        {
                            Id = 7,
                            Annual = "2024, özellikle ilişkiler ve ortaklıklar açısından önemli bir yıl olacak.",
                            Daily = "İlişkilerinizde denge kurmakta başarılı olacaksınız. Estetik konularda şanslı bir gün.",
                            HoroscopeId = 7,
                            Monthly = "Venüs'ün etkisiyle aşk hayatınızda güzel gelişmeler olacak. Sanat ve güzellik alanlarında başarılı olacaksınız.",
                            Name = "Terazi Burcu"
                        },
                        new
                        {
                            Id = 8,
                            Annual = "2024'te özellikle finansal konularda şanslı olacaksınız. Plüton'un desteğiyle büyük değişimler yaşayabilirsiniz.",
                            Daily = "Sezgileriniz güçlü. Finansal konularda önemli kararlar alabilirsiniz.",
                            HoroscopeId = 8,
                            Monthly = "Mars'ın etkisiyle enerjiniz yüksek olacak. Gizli kalmış konular aydınlanabilir.",
                            Name = "Akrep Burcu"
                        },
                        new
                        {
                            Id = 9,
                            Annual = "2024, özellikle eğitim ve yurtdışı konularında şanslı olacağınız bir yıl.",
                            Daily = "Jüpiter'in etkisiyle şansınız açık. Yeni öğrenme fırsatları karşınıza çıkabilir.",
                            HoroscopeId = 9,
                            Monthly = "Seyahat ve eğitim konularında şanslı bir ay. Yurtdışı bağlantılı işler gündeme gelebilir.",
                            Name = "Yay Burcu"
                        },
                        new
                        {
                            Id = 10,
                            Annual = "2024, kariyer hedeflerinize ulaşacağınız bir yıl olacak. İş hayatınızda yükseliş var.",
                            Daily = "Kariyer konularında önemli gelişmeler yaşanabilir. Disiplininiz başarı getirecek.",
                            HoroscopeId = 10,
                            Monthly = "Satürn'ün etkisiyle iş hayatınızda önemli sorumluluklar alabilirsiniz.",
                            Name = "Oğlak Burcu"
                        },
                        new
                        {
                            Id = 11,
                            Annual = "2024, teknoloji ve bilim alanlarında başarılı olacağınız bir yıl. Sosyal çevreniz genişleyecek.",
                            Daily = "Yenilikçi fikirleriniz dikkat çekecek. Teknoloji ile ilgili konularda şanslısınız.",
                            HoroscopeId = 11,
                            Monthly = "Uranüs'ün etkisiyle beklenmedik fırsatlar karşınıza çıkabilir. Sosyal çevreniz genişleyecek.",
                            Name = "Kova Burcu"
                        },
                        new
                        {
                            Id = 12,
                            Annual = "2024, spirituel konularda gelişim göstereceğiniz bir yıl. Yaratıcılığınız zirve yapacak.",
                            Daily = "Sanatsal yetenekleriniz ön planda. Ruhsal konularda hassas bir gün.",
                            HoroscopeId = 12,
                            Monthly = "Neptün'ün etkisiyle sezgileriniz güçlenecek. Sanatsal projeler için uygun bir ay.",
                            Name = "Balık Burcu"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.HoroscopeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoroscopeNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HoroscopeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoroscopeNames = "Koç,Aslan,Yay",
                            Image = "/Ui/assets/img/AtesGrubu.jpg",
                            Name = "Ateş Grubu"
                        },
                        new
                        {
                            Id = 2,
                            HoroscopeNames = "Boğa,Başak,Oğlak",
                            Image = "/Ui/assets/img/ToprakGrubu.jpg",
                            Name = "Toprak Grubu"
                        },
                        new
                        {
                            Id = 3,
                            HoroscopeNames = "İkizler,Terazi,Kova",
                            Image = "/Ui/assets/img/HavaGrubu.jpg",
                            Name = "Hava Grubu"
                        },
                        new
                        {
                            Id = 4,
                            HoroscopeNames = "Yengeç,Akrep,Balık",
                            Image = "/Ui/assets/img/SuGrubu.jpg",
                            Name = "Su Grubu"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AstroMap Workshop",
                            Title = "AstroMap Workshop, katilimcilara dogum haritalarini derinlemesine analiz etmeyi ve hayatlarindaki potansiyel yollari kesfetmeyi ögretir. Kendi astrolojik haritanizi çözerek, kisisel gelisiminiz için güçlü bir rehber olusturabilirsiniz."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tarot Workshop",
                            Title = "Tarot Workshop, kartlar aracılığıyla kendinizle ve evrenle daha derin bir bağlantı kurmanızı sağlar. Tarot^un sembollerini öğrenerek, hayatınızdaki sorulara rehberlik edecek anlamlı okumalar yapmayı öğrenebilirsiniz."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reiki Workshop",
                            Title = "Reiki Workshop, katilimcilara bedensel, zihinsel ve duygusal dengeyi saglamak için Reiki enerjisini nasil kullanacaklarini ögretir. Enerji çalismalari ile kendinizi iyilestirmenin ve çevrenizdeki insanlara sifa vermenin yollarini kesfedin."
                        },
                        new
                        {
                            Id = 4,
                            Name = "Evren Workshop",
                            Title = "Evren Workshop, kişisel yaşam alanlarınıza enerjiyi nasıl yönlendirebileceğinizi ve mekanlarınızda dengeyi nasıl sağlayacağınızı öğretir. Feng Shui tekniklerini kullanarak, evinizde huzur ve olumlu enerji akışını sağlamak mümkün."
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fab fa-instagram",
                            Name = "Instagram",
                            Url = "https://instagram.com/astromistik"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fab fa-facebook",
                            Name = "Facebook",
                            Url = "https://facebook.com/astromistik"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fab fa-twitter",
                            Name = "Twitter",
                            Url = "https://twitter.com/astromistik"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fab fa-youtube",
                            Name = "YouTube",
                            Url = "https://youtube.com/astromistik"
                        });
                });

            modelBuilder.Entity("AstrolojiApp.Entity.Concrete.HoroscopeComment", b =>
                {
                    b.HasOne("AstrolojiApp.Entity.Concrete.Horoscope", "Horoscope")
                        .WithMany()
                        .HasForeignKey("HoroscopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horoscope");
                });
#pragma warning restore 612, 618
        }
    }
}
